---
- name: MAIN | Deploying subtasks
  hosts: all
  remote_user: root
  vars:
    install_packages:
    - libselinux-python
    - nmap
    - nano
    - ntp
    - screen
    - sysstat

  tasks:
#    - include: plays/motd_customize.yaml
#    - include: plays/package_install.yaml
#    - include: plays/users.yaml
    - include: plays/figlet.yaml
